groups:
- testgrp
minions_to_add:
- mars
- saturn
sqlite_db: "/run/11112023_testgrp_t7udp.db"
qualifying_only: true
log_level: info
timeout: 3
gather_job_timeout: 15
email_interval: 8
logfile: "/var/log/patching/sumapatching.log"
salt_master_address: 192.168.122.23
salt_api_port: 8000
salt_user: mysalt
salt_password: mytest
salt_diskspace_grains_key: btrfs:for_patching
salt_diskspace_grains_value: ok
salt_no_upgrade_exception_key: no_patch
salt_no_upgrade_exception_value: 'true'
salt_prep_state: orch.prepatch_states
salt_post_state: orch.postpatch_states
jobchecker_timeout: 90
jobchecker_emails:
- bo.jin@jinbo01.com
- bo.jin@suseconsulting.ch
t7user: t7udp
authentication_token: R2bfp223Qsk-pX970Jw8tyJUChT4-e2J8anZ4G4n4IM=
tracking_file_directory: "/var/log/sumapatch/"
patch_level: 2023-Q4
workflow:
- assign_channels: 1
- package_updates: 2
- package_update_reboot: 3
- package_refresh: 4
- waiting: 5
- spmigration_dryrun: 6
- spmigration_run: 7
- spmigration_reboot: 8
- spmigration_package_refresh: 9
- post_migration: 10
assign_channels:
- assign_channel:
    current_base_channel: mytest-prd-sle-product-sles_sap15-sp4-pool-x86_64
    new_base_prefix: mytest-test-
- assign_channel:
    current_base_channel: mysle15sp3-prd-sle-product-sles15-sp3-pool-x86_64
    new_base_prefix: ''
products:
- product:
    ident: '1565,1576,1609,1592,1572,1616,1580,935,1633,1614'
    name: SUSE Linux Enterprise Server for SAP Applications 15 SP5 x86_64
    base_channel_label: sle-product-sles_sap15-sp5-pool-x86_64
    clm_project_label: mysap15sp5
    optionalChildChannels:
      - old_channel: rke2-sles15sp4
        new_channel: rke2-sles15sp5
- product:
    ident: '1396,1423,1431,1411,1415,935,1403,1438'
    name: SUSE Linux Enterprise Server 15 SP4 x86_64
    base_channel_label: sle-product-sles15-sp4-pool-x86_64
    clm_project_label:
    optionalChildChannels:
      - old_channel: rke2-sles15sp4
        new_channel: rke2-sles15sp5
      - old_channel: rke2-common-15sp4
        new_channel: rke2-common-15sp5